import type { TableColumn } from "./table-utils";
import { PURCHASE_CURRENCY_OPTIONS } from "./purchase-order-form";
import { REQUEST_TYPE_OPTIONS } from "./request-type";
import { purchaseOrderPlanFieldSpecs, purchaseOrderSnFieldSpecs } from "./purchase-order-demand-plan-fields";

export type FieldType = "text" | "number" | "money" | "percentage" | "date" | "datetime" | "boolean" | "switch" | "textarea" | "select" | "lineType";

export type EntityField = TableColumn & {
  type?: FieldType;
  placeholder?: string;
  required?: boolean;
  readonly?: boolean;
  hidden?: boolean;
  lookupSource?: "countries" | "datacenters" | "delivery-locations" | "delivery-contacts" | "b6-type-configs";
  options?: Array<{ label: string; value: string }>;
};

export type EntityConfig = {
  key: string;
  title: string;
  table: string;
  primaryKey: string;
  uniqueKeys?: string[];
  navGroup: string;
  route: string;
  description: string;
  listFields: EntityField[];
  formFields: EntityField[];
  filters: EntityField[];
  defaultSort?: string;
  showSequence?: boolean;
};

export type NavGroup = {
  title: string;
  items: EntityConfig[];
  children?: Array<{
    title: string;
    items: EntityConfig[];
  }>;
};

export const entityConfigs: EntityConfig[] = [
  {
    key: "countries",
    title: "国家管理",
    table: "countries",
    primaryKey: "code",
    navGroup: "基础信息",
    route: "/master-data/countries",
    description: "维护国家代码及中英文名称。",
    filters: [{ key: "keyword", label: "国家", placeholder: "请输入国家代码或名称" }],
    listFields: [
      { key: "code", label: "国家代码" },
      { key: "nameZh", label: "国家中文名" },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
    ],
    formFields: [
      { key: "code", label: "国家代码", required: true },
      { key: "nameZh", label: "国家中文名", required: true },
      { key: "nameEn", label: "国家英文名" },
      { key: "nameLocal", label: "当地语言名称" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
    ],
  },
  {
    key: "delivery-locations",
    title: "交付地址",
    table: "deliverylocations",
    primaryKey: "locationId",
    navGroup: "基础信息",
    route: "/master-data/delivery-locations",
    description: "维护仓库、办公室、机房、Broker 等交付站点。",
    filters: [
      { key: "keyword", label: "地点", placeholder: "请输入地点ID或名称" },
      { key: "countryCode", label: "国家", placeholder: "请选择国家" },
    ],
    listFields: [
      { key: "locationId", label: "地点ID" },
      { key: "countryCode", label: "国家" },
      { key: "locationType", label: "地点类型" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址" },
    ],
    formFields: [
      { key: "locationId", label: "地点ID", required: true },
      { key: "countryCode", label: "国家代码", required: true },
      { key: "locationType", label: "地点类型", required: true },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
      { key: "fullAddress", label: "详细地址", type: "textarea" },
    ],
  },
  {
    key: "delivery-contacts",
    title: "收件人信息",
    table: "deliverycontacts",
    primaryKey: "contactId",
    navGroup: "基础信息",
    route: "/master-data/delivery-contacts",
    description: "维护交付地址对应的联系人、电话和邮箱。",
    filters: [{ key: "keyword", label: "联系人", placeholder: "请输入姓名、电话或邮箱" }],
    listFields: [
      { key: "contactId", label: "联系人ID" },
      { key: "locationId", label: "所属地点" },
      { key: "name", label: "姓名" },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
    formFields: [
      { key: "contactId", label: "联系人ID", required: true },
      { key: "locationId", label: "所属地点ID", required: true },
      { key: "name", label: "姓名", required: true },
      { key: "phone", label: "电话" },
      { key: "email", label: "邮箱" },
    ],
  },
  {
    key: "datacenters",
    title: "机房管理",
    table: "datacenters",
    primaryKey: "dcCode",
    navGroup: "基础信息",
    route: "/master-data/datacenters",
    description: "维护机房与物理交付地址的绑定关系。",
    filters: [{ key: "keyword", label: "机房", placeholder: "请输入机房ID或名称" }],
    listFields: [
      { key: "dcCode", label: "机房ID" },
      { key: "locationId", label: "物理地址" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
    ],
    formFields: [
      { key: "dcCode", label: "机房ID", required: true },
      { key: "locationId", label: "物理地址", required: true, type: "textarea" },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
    ],
  },
  {
    key: "suppliers",
    title: "供应商管理",
    table: "suppliers",
    primaryKey: "supplierId",
    navGroup: "基础信息",
    route: "/master-data/suppliers",
    description: "维护 ODM 供应商信息。",
    filters: [{ key: "keyword", label: "供应商", placeholder: "请输入供应商代码或名称" }],
    listFields: [
      { key: "supplierId", label: "供应商ID" },
      { key: "supplierCode", label: "供应商代码" },
      { key: "name", label: "名称" },
    ],
    formFields: [
      { key: "supplierId", label: "供应商ID", required: true },
      { key: "supplierCode", label: "供应商代码", required: true },
      { key: "name", label: "名称", required: true },
    ],
  },
  {
    key: "instance-models",
    title: "实例型号",
    table: "instancemodels",
    primaryKey: "deviceCode",
    navGroup: "基础信息",
    route: "/master-data/instance-models",
    description: "维护设备编码、机型和实例型号名称。",
    filters: [
      { key: "keyword", label: "实例型号", placeholder: "请输入设备编码、机型或名称" },
    ],
    listFields: [
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称" },
      { key: "nameEn", label: "英文名称" },
      { key: "b6Type", label: "默认B6类型" },
    ],
    formFields: [
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", required: true },
      { key: "xxllCode", label: "xxll编码" },
      { key: "nameZh", label: "中文名称", required: true },
      { key: "nameEn", label: "英文名称" },
      { key: "b6Type", label: "默认B6类型", placeholder: "选择或搜索B6类型", lookupSource: "b6-type-configs" },
    ],
  },
  {
    key: "undertaking-units",
    title: "承接单位管理",
    table: "undertakingunits",
    primaryKey: "undertakingUnitId",
    uniqueKeys: ["undertakingUnitCode"],
    navGroup: "基础信息",
    route: "/master-data/undertaking-units",
    description: "维护承接单位ID、承接单位代码和名称。",
    filters: [{ key: "keyword", label: "承接单位", placeholder: "请输入承接单位代码或名称" }],
    listFields: [
      { key: "undertakingUnitId", label: "承接单位ID" },
      { key: "undertakingUnitCode", label: "承接单位代码" },
      { key: "name", label: "名称" },
    ],
    formFields: [
      { key: "undertakingUnitId", label: "承接单位ID", required: true },
      { key: "undertakingUnitCode", label: "承接单位代码", required: true },
      { key: "name", label: "名称", required: true },
    ],
  },
  {
    key: "customers",
    title: "客户管理",
    table: "customers",
    primaryKey: "customerId",
    uniqueKeys: ["customerCode"],
    navGroup: "基础信息",
    route: "/master-data/customers",
    description: "维护客户ID、客户代码和名称。",
    filters: [{ key: "keyword", label: "客户", placeholder: "请输入客户代码或名称" }],
    listFields: [
      { key: "customerId", label: "客户ID" },
      { key: "customerCode", label: "客户代码" },
      { key: "name", label: "名称" },
    ],
    formFields: [
      { key: "customerId", label: "客户ID", required: true },
      { key: "customerCode", label: "客户代码", required: true },
      { key: "name", label: "名称", required: true },
    ],
  },
  {
    key: "instance-contracts",
    title: "实例合同",
    table: "instancecontracts",
    primaryKey: "id",
    uniqueKeys: ["contractNo", "countryCode", "deviceCode"],
    navGroup: "合同管理",
    route: "/contracts/instance-contracts",
    description: "维护实例合同、国家、实例型号与分阶段含税单价。",
    filters: [
      { key: "keyword", label: "实例合同", placeholder: "请输入合同号、国家、设备编码或机型" },
    ],
    listFields: [
      { key: "id", label: "内部ID", defaultVisible: false },
      { key: "contractNo", label: "合同号" },
      { key: "countryCode", label: "国家" },
      { key: "deviceCode", label: "设备编码" },
      { key: "modelCode", label: "机型" },
      { key: "instanceModelEn", label: "实例型号（英文）" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "money" },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "money" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "合同号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "modelCode", label: "机型", readonly: true },
      { key: "instanceModelEn", label: "实例型号（英文）", readonly: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "first24MonthPriceUSD", label: "前24个月含税单价", type: "money", required: true },
      { key: "next36MonthPriceUSD", label: "后36个月含税单价", type: "money", required: true },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "requests",
    title: "需求单",
    table: "requests",
    primaryKey: "requestNo",
    navGroup: "客户需求",
    route: "/requests/orders",
    description: "以主从表单维护客户需求单和需求明细。",
    filters: [
      { key: "keyword", label: "需求单", placeholder: "请输入需求单号、合同号或批次" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "requestNo", label: "需求单号" },
      { key: "countryCode", label: "国家" },
      { key: "contractNo", label: "合同号" },
      { key: "batchName", label: "批次名称" },
      { key: "requestType", label: "类型" },
      { key: "status", label: "状态" },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "requestNo", label: "需求单号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "batchName", label: "批次名称", required: true },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS, required: true },
      { key: "status", label: "状态", required: true },
      { key: "plannedDeliveryDate", label: "计划交付日期", type: "date" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "request-items",
    title: "需求明细一览",
    table: "requestitems",
    primaryKey: "id",
    navGroup: "客户需求",
    route: "/requests/items",
    description: "跨批次集中查看所有需求明细。",
    filters: [
      { key: "keyword", label: "需求明细", placeholder: "请输入需求单号、设备编码或供应商" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "requestNo", label: "需求单号" },
      { key: "requestType", label: "类型" },
      { key: "deviceCode", label: "设备编码" },
      { key: "supplierId", label: "供应商" },
      { key: "undertakingUnitId", label: "承接单位" },
      { key: "customerCode", label: "客户" },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "requestNo", label: "需求单号", required: true },
      { key: "requestType", label: "类型", readonly: true },
      { key: "deviceCode", label: "设备编码", required: true },
      { key: "supplierId", label: "供应商ID", required: true },
      { key: "undertakingUnitId", label: "承接单位ID", required: true },
      { key: "customerId", label: "客户ID" },
      { key: "requestedAt", label: "需求时间", type: "date" },
      { key: "quantity", label: "节点数量", type: "number", required: true },
    ],
  },
  {
    key: "purchase-orders",
    title: "采购订单",
    table: "purchaseorders",
    primaryKey: "purchaseOrderId",
    navGroup: "采购管理",
    route: "/purchase/orders",
    description: "以主从表单维护 PO 主单和采购明细。",
    filters: [
      { key: "keyword", label: "采购订单", placeholder: "请输入PO订单号或币种" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "poNo", label: "PO订单号" },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态" },
      { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
    ],
    formFields: [
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestNo", label: "来源需求单号" },
      { key: "status", label: "采购状态", required: true },
      { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
      { key: "releasedAt", label: "下发日期", type: "date" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "purchase-order-items",
    title: "采购明细一览",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "采购管理",
    route: "/purchase/items",
    description: "集中查看所有 PO 采购明细。",
    filters: [
      { key: "keyword", label: "采购明细", placeholder: "请输入PO订单号或需求明细ID" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "requestItemId", label: "需求明细" },
      { key: "requestType", label: "类型" },
      { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
      { key: "taxSurcharge", label: "税费加成", type: "money" },
      { key: "unitPrice", label: "含税单价", type: "money" },
      { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
      { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
      { key: "taxSurcharge", label: "税费加成", type: "money" },
      { key: "unitPrice", label: "含税单价", type: "money" },
      { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
      { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
      { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
      { key: "softwareCoefficient", label: "软件系数", type: "number" },
      { key: "totalCoefficient", label: "总系数", type: "number" },
    ],
  },
  {
    key: "shipments",
    title: "物流列表",
    table: "shipments",
    primaryKey: "shipmentId",
    navGroup: "物流管理",
    route: "/shipments",
    description: "管理 PO 发运、交付快照和物流时间线。",
    defaultSort: "createdAt DESC",
    filters: [
      { key: "keyword", label: "物流", placeholder: "请输入物流ID、PO订单号或收件人" },
      { key: "countryCode", label: "国家", type: "select", lookupSource: "countries" },
      { key: "transportMode", label: "运输方式", placeholder: "请选择运输方式" },
      {
        key: "receiptStatus",
        label: "签收状态",
        type: "select",
        options: [
          { label: "已签收", value: "received" },
          { label: "未签收", value: "unreceived" },
        ],
      },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "shipmentId", label: "物流ID" },
      { key: "poNo", label: "PO订单号" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "dcNameZh", label: "机房" },
      { key: "destinationAddress", label: "收货地址" },
      { key: "recipientName", label: "收件人" },
      { key: "snapshotDestinationAddress", label: "交付地址快照", defaultVisible: false },
      { key: "snapshotRecipientName", label: "收件人快照", defaultVisible: false },
      { key: "snapshotRecipientPhone", label: "收件电话快照", defaultVisible: false },
      { key: "transportMode", label: "运输方式" },
      { key: "isReceived", label: "是否签收", type: "boolean" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
      { key: "createdAt", label: "创建时间", type: "datetime", defaultVisible: false },
      { key: "updatedAt", label: "更新时间", type: "datetime", defaultVisible: false },
    ],
    formFields: [
      { key: "shipmentId", label: "物流ID", required: true },
      { key: "poNo", label: "PO订单号", required: true },
      { key: "batchName", label: "批次号" },
      { key: "purchaseOrderItemId", label: "采购明细ID" },
      { key: "deviceCode", label: "实例编码" },
      { key: "nameEn", label: "实例名称（英文）" },
      { key: "dcCode", label: "机房ID", lookupSource: "datacenters", placeholder: "输入机房ID或中文名称搜索" },
      { key: "dcNameZh", label: "机房中文名称" },
      { key: "destinationLocationId", label: "目的地点ID", lookupSource: "delivery-locations", placeholder: "输入地点ID、名称或地址搜索" },
      { key: "recipientContactId", label: "收件联系人ID", lookupSource: "delivery-contacts", placeholder: "输入联系人ID、姓名或电话搜索" },
      { key: "snapshotDestinationAddress", label: "交付地址快照", type: "textarea" },
      { key: "snapshotRecipientName", label: "收件人快照" },
      { key: "snapshotRecipientPhone", label: "收件电话快照" },
      { key: "transportMode", label: "运输方式" },
      { key: "crd", label: "CRD", type: "date" },
      { key: "apdAt", label: "APD交单", type: "date" },
      { key: "pickupAt", label: "ASD提货", type: "date" },
      { key: "departedAt", label: "起飞/开船", type: "date" },
      { key: "arrivedAt", label: "到港", type: "date" },
      { key: "customsClearedAt", label: "清关完成", type: "date" },
      { key: "deliveredAt", label: "派送", type: "date" },
    ],
  },
  {
    key: "billing-available",
    title: "待生成月账单实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/billing-available",
    description: "从已确认下单且尚未生成月账单台账的实例中生成60个月账单。",
    filters: [
      { key: "keyword", label: "待生成月账单", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "billing-ledgers",
    title: "月账单台账",
    table: "billinginstanceledgers",
    primaryKey: "ledgerId",
    navGroup: "财务管理",
    route: "/finance/billing-ledgers",
    description: "查看已确认月账单实例的合同价格锁定信息。",
    filters: [
      { key: "keyword", label: "月账单台账", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "ledgerId", label: "台账ID" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "money" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "money" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    formFields: [
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "actualCurrency", label: "实际币种" },
      { key: "actualUnitPrice", label: "实际单价", type: "money" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "contractCurrency", label: "合同币种" },
      { key: "first24MonthPrice", label: "前24个月合同价", type: "money" },
      { key: "next36MonthPrice", label: "后36个月合同价", type: "money" },
      { key: "startMonth", label: "起始核销月份", type: "date" },
      { key: "status", label: "状态" },
    ],
    defaultSort: "confirmedAt DESC",
  },
  {
    key: "monthly-billing-writeoffs",
    title: "月账单每月明细",
    table: "monthlybillingwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-billing-writeoffs",
    description: "查看月账单台账生成的60个月实例核销明细。",
    filters: [
      { key: "keyword", label: "月账单明细", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月账单实例价格（含税）", type: "money" },
      { key: "monthlyTotalAmount", label: "月账单金额（含税）", type: "money" },
      { key: "selfCalculatedUnitPrice", label: "24个月实例单价（含税自算）", type: "number" },
      { key: "differenceUnitPrice", label: "结差差额单价", type: "money" },
      { key: "differenceTotalPrice", label: "结差差额总价", type: "money" },
      { key: "stage", label: "阶段" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "ledgerId", label: "台账ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number" },
      { key: "stage", label: "阶段" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "instanceContractNo", label: "实例合同号" },
      { key: "currency", label: "币种" },
      { key: "monthlyAmount", label: "月账单实例价格（含税）", type: "money" },
      { key: "monthlyTotalAmount", label: "月账单金额（含税）", type: "money" },
      { key: "selfCalculatedUnitPrice", label: "24个月实例单价（含税自算）", type: "number" },
      { key: "differenceUnitPrice", label: "结差差额单价", type: "money" },
      { key: "differenceTotalPrice", label: "结差差额总价", type: "money" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "billing-adjustments",
    title: "实例合同调整单",
    table: "billingadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "合同管理",
    route: "/finance/billing-adjustments",
    description: "维护特定批次、特定实例在某个生效月份之后的月账单价格调整。",
    filters: [{ key: "keyword", label: "调整单", placeholder: "请输入调整单号、合同号、国家、批次或实例编码" }],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "instanceContractNo", label: "实例合同单号" },
      { key: "status", label: "状态" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "reason", label: "调整原因" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "instanceContractNo", label: "实例合同单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "billing-statements",
    title: "月账单对账单",
    table: "billingstatementsnapshots",
    primaryKey: "snapshotNo",
    navGroup: "财务管理",
    route: "/finance/billing-statements",
    description: "按国家、期间和币种生成月账单对账单，确认后冻结并按模板导出 Excel。",
    filters: [
      { key: "keyword", label: "对账单", placeholder: "请输入快照编号、国家或币种" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
    ],
    listFields: [
      { key: "snapshotNo", label: "快照编号" },
      { key: "countryCode", label: "国家" },
      { key: "startDate", label: "起始日期", type: "date" },
      { key: "endDate", label: "终止日期", type: "date" },
      { key: "currencySummary", label: "币种汇总" },
      { key: "totalQuantity", label: "总数量", type: "number" },
      { key: "totalAmount", label: "总金额", type: "money" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
    ],
    formFields: [
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "countryCode", label: "国家", required: true },
      { key: "startDate", label: "起始日期", type: "date", required: true },
      { key: "endDate", label: "终止日期", type: "date", required: true },
      { key: "currencySummary", label: "币种汇总" },
      { key: "totalQuantity", label: "总数量", type: "number" },
      { key: "totalAmount", label: "总金额", type: "money" },
      { key: "itemCount", label: "明细数量", type: "number" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "service-fees",
    title: "服务费核算",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fees",
    description: "按月度月账单核销总额减预付款核销金额，实时核算服务费并生成服务费对账单草稿。",
    filters: [
      { key: "keyword", label: "服务费核算", placeholder: "请输入国家、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "快照编号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitId", label: "承接单位" },
      { key: "supplierId", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
  },
  {
    key: "service-fee-snapshots",
    title: "服务费对账单",
    table: "servicefeesnapshots",
    primaryKey: "snapshotNo",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshots",
    description: "按国家和核销月份管理服务费对账单、确认状态、开票状态及发票附件。",
    filters: [
      { key: "keyword", label: "对账单", placeholder: "请输入对账单号、国家或附件名" },
      { key: "writeOffMonth", label: "核销月份", placeholder: "核销月份", type: "date" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "status", label: "确认状态", type: "select", options: [{ label: "未确认", value: "未确认" }, { label: "已确认", value: "已确认" }] },
      { key: "invoiceStatus", label: "开票状态", type: "select", options: [{ label: "未开票", value: "未开票" }, { label: "已开票", value: "已开票" }] },
      { key: "repaymentStatus", label: "回款状态", type: "select", options: [{ label: "未回款", value: "未回款" }, { label: "已回款", value: "已回款" }] },
    ],
    listFields: [
      { key: "snapshotNo", label: "对账单号" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "status", label: "状态" },
      { key: "billingTotal", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentTotal", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeTotal", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeTotalExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "money" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "money" },
      { key: "repaymentStatus", label: "是否回款", type: "switch" },
      { key: "receivingUnitCode", label: "收款单位" },
      { key: "payerCustomerCode", label: "付款单位" },
      { key: "repaymentCurrency", label: "回款币种" },
      { key: "repaymentAmount", label: "回款金额", type: "money" },
      { key: "repaymentDate", label: "回款日期", type: "date" },
      { key: "invoiceStatus", label: "开票状态" },
      { key: "invoiceOriginalName", label: "发票附件" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    formFields: [
      { key: "snapshotNo", label: "对账单号", required: true },
      { key: "status", label: "状态" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "billingTotal", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentTotal", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeTotal", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeTotalExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "instanceServiceFeeTotal", label: "实例服务费合计", type: "money" },
      { key: "feeServiceFeeTotal", label: "非实例费用合计", type: "money" },
      { key: "repaymentStatus", label: "是否回款", type: "switch" },
      { key: "receivingUnitId", label: "收款单位" },
      { key: "payerCustomerId", label: "付款单位" },
      { key: "repaymentCurrency", label: "回款币种" },
      { key: "repaymentAmount", label: "回款金额", type: "money" },
      { key: "repaymentDate", label: "回款日期", type: "date" },
      { key: "invoiceStatus", label: "开票状态" },
      { key: "invoiceOriginalName", label: "发票附件" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "writeOffMonth DESC, createdAt DESC",
  },
  {
    key: "service-fee-snapshot-items",
    title: "服务费对账单明细",
    table: "servicefeesnapshotitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/service-fee-snapshot-items",
    description: "查看服务费对账单中冻结保存的明细行。",
    filters: [
      { key: "keyword", label: "对账单明细", placeholder: "请输入对账单号、批次、需求单、PO或实例编码" },
      { key: "snapshotNo", label: "对账单号", placeholder: "对账单号" },
      { key: "countryCode", label: "国家", placeholder: "国家" },
      { key: "batchName", label: "批次", placeholder: "批次" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "snapshotNo", label: "对账单号" },
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "countryCode", label: "国家" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "snapshotNo", label: "对账单号", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "countryCode", label: "国家" },
      { key: "vatRate", label: "增值税税率（%）", type: "percentage" },
      { key: "batchName", label: "批次" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "billingCurrency", label: "月账单币种" },
      { key: "billingAmount", label: "月账单总额（含税）", type: "money" },
      { key: "prepaymentCurrency", label: "预付款币种" },
      { key: "prepaymentAmount", label: "预付款核销金额（含税）", type: "money" },
      { key: "serviceFeeAmount", label: "月度服务费（含税）", type: "money" },
      { key: "serviceFeeAmountExcludingTax", label: "月度服务费（未税）", type: "money" },
      { key: "billingSourceIds", label: "月账单来源ID" },
      { key: "prepaymentSourceIds", label: "预付款来源ID" },
      { key: "prepaymentContractNos", label: "预付款合同号" },
      { key: "sourceNote", label: "来源说明" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-available",
    title: "待生成预付款实例",
    table: "purchaseorderitems",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/prepayment-available",
    description: "从已下单采购实例中勾选生成预付款合同草稿。",
    filters: [
      { key: "keyword", label: "待生成实例", placeholder: "请输入批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "采购明细ID" },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号" },
      { key: "requestItemId", label: "需求明细ID" },
      { key: "requestType", label: "类型" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
    formFields: [
      { key: "id", label: "采购明细ID", required: true },
      { key: "countryCode", label: "国家" },
      { key: "poNo", label: "PO单号", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "requestType", label: "类型" },
      { key: "unitPrice", label: "实际单价", type: "number" },
    ],
  },
  {
    key: "prepayment-contracts",
    title: "预付款合同",
    table: "prepaymentcontracts",
    primaryKey: "contractNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-contracts",
    description: "管理预付款合同草稿、确认状态和合同总金额。",
    filters: [
      { key: "keyword", label: "预付款合同", placeholder: "请输入合同号、状态或币种" },
      { key: "status", label: "状态", placeholder: "请选择状态" },
    ],
    listFields: [
      { key: "contractNo", label: "预付款合同号" },
      { key: "status", label: "状态" },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "currency", label: "币种" },
      { key: "effectiveDate", label: "生效日期", type: "date" },
      { key: "totalAmount", label: "合同总金额", type: "number" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "monthly-prepayment-writeoffs",
    title: "预付款每月核销明细",
    table: "monthlyprepaymentwriteoffs",
    primaryKey: "id",
    navGroup: "财务管理",
    route: "/finance/monthly-prepayment-writeoffs",
    description: "按月份查看已确认预付款合同生成的核销金额。",
    filters: [
      { key: "keyword", label: "月度核销", placeholder: "请输入合同号、批次、需求单、PO或实例编码" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "writeOffMonth", label: "核销月份", type: "date" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "undertakingUnitCode", label: "承接单位" },
      { key: "supplierCode", label: "供应商" },
      { key: "customerCode", label: "客户" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "money" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    formFields: [
      { key: "id", label: "月度核销ID", required: true },
      { key: "contractNo", label: "预付款合同号", required: true },
      { key: "contractLineId", label: "合同明细ID", required: true },
      { key: "writeOffMonth", label: "核销月份", type: "date", required: true },
      { key: "monthIndex", label: "月份序号", type: "number", required: true },
      { key: "totalMonths", label: "总月份", type: "number", required: true },
      { key: "currency", label: "币种" },
      { key: "originalAmount", label: "合同总价", type: "number" },
      { key: "monthlyAmount", label: "月核销金额", type: "money" },
      { key: "lineType", label: "明细类型", type: "lineType" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "requestNo", label: "需求单号" },
      { key: "poNo", label: "PO单号" },
      { key: "deviceCode", label: "实例编码" },
      { key: "requestType", label: "类型" },
      { key: "modelCode", label: "机型" },
      { key: "nameEn", label: "英文名称" },
      { key: "quantity", label: "数量", type: "number" },
      { key: "sourceType", label: "来源" },
      { key: "adjustmentNo", label: "调整单号" },
    ],
    defaultSort: "writeOffMonth DESC",
  },
  {
    key: "prepayment-writeoff-adjustments",
    title: "预付款核销调整单",
    table: "prepaymentwriteoffadjustments",
    primaryKey: "adjustmentNo",
    navGroup: "财务管理",
    route: "/finance/prepayment-writeoff-adjustments",
    description: "针对特定批次、实例、月份调整预付款每月核销金额。",
    filters: [
      { key: "keyword", label: "调整单", placeholder: "请输入调整单号、合同号、批次或实例编码" },
    ],
    listFields: [
      { key: "adjustmentNo", label: "调整单号" },
      { key: "status", label: "状态" },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "itemCount", label: "明细数量", type: "number" },
      { key: "differenceTotal", label: "调整差额合计", type: "number" },
      { key: "reason", label: "调整原因" },
      { key: "confirmedAt", label: "确认时间", type: "datetime" },
      { key: "createdAt", label: "创建时间", type: "datetime" },
      { key: "updatedAt", label: "更新时间", type: "datetime" },
    ],
    formFields: [
      { key: "adjustmentNo", label: "调整单号", required: true },
      { key: "status", label: "状态", required: true },
      { key: "countryCode", label: "国家" },
      { key: "batchName", label: "批次号" },
      { key: "contractNo", label: "预付款合同号" },
      { key: "reason", label: "调整原因", type: "textarea" },
    ],
    defaultSort: "createdAt DESC",
  },
  {
    key: "prepayment-contract-items",
    title: "预付款合同明细",
    table: "prepaymentcontractitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/finance/prepayment-contract-items",
    description: "管理预付款合同下的支付明细。",
    filters: [
      { key: "keyword", label: "预付款", placeholder: "请输入合同号、币种或明细ID" },
      { key: "requestType", label: "类型", type: "select", options: REQUEST_TYPE_OPTIONS },
    ],
    listFields: [
      { key: "id", label: "明细ID" },
      { key: "contractNo", label: "合同号" },
      { key: "requestType", label: "类型" },
      { key: "prepaymentAmount", label: "预付款金额", type: "money" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
    formFields: [
      { key: "id", label: "明细ID", required: true },
      { key: "contractNo", label: "合同号", required: true },
      { key: "requestType", label: "类型", readonly: true },
      { key: "prepaymentAmount", label: "预付款金额", type: "money" },
      { key: "currency", label: "币种" },
      { key: "usdRate", label: "美元汇率", type: "number" },
      { key: "paymentDate", label: "支付日期", type: "date" },
    ],
  },
  {
    key: "write-off-items",
    title: "核销明细",
    table: "writeoffitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/finance/write-off-items",
    description: "管理预付款与需求明细之间的核销关系。",
    filters: [{ key: "keyword", label: "核销", placeholder: "请输入核销ID或需求明细ID" }],
    listFields: [
      { key: "id", label: "核销ID" },
      { key: "requestItemId", label: "需求明细" },
      { key: "prepaymentContractItemId", label: "预付款明细" },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "money" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
    formFields: [
      { key: "id", label: "核销ID", required: true },
      { key: "requestItemId", label: "需求明细ID", required: true },
      { key: "prepaymentContractItemId", label: "预付款明细ID", required: true },
      { key: "prepaymentAmountUSD", label: "预付款USD", type: "money" },
      { key: "writeOffCurrency", label: "核销币种" },
      { key: "writeOffRate", label: "核销汇率", type: "number" },
      { key: "startMonth", label: "起始月份", type: "date" },
      { key: "totalMonths", label: "核销月数", type: "number" },
    ],
  },
];

const purchaseOrderConfig = entityConfigs.find((entity) => entity.key === "purchase-orders");
if (purchaseOrderConfig) {
  purchaseOrderConfig.primaryKey = "purchaseOrderId";
  purchaseOrderConfig.listFields = [
    { key: "purchaseOrderId", label: "系统采购ID", defaultVisible: false },
    { key: "poNo", label: "PO订单号" },
    { key: "requestNo", label: "来源需求单号" },
    { key: "countryCode", label: "国家" },
    { key: "requestType", label: "类型" },
    { key: "status", label: "采购状态" },
    { key: "currency", label: "币种", type: "select", options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
    { key: "releasedAt", label: "下发日期", type: "date" },
    { key: "createdAt", label: "创建时间", type: "datetime" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ];
  purchaseOrderConfig.formFields = [
    { key: "purchaseOrderId", label: "系统采购ID", required: true },
    { key: "poNo", label: "PO订单号", required: true },
    { key: "requestNo", label: "来源需求单号" },
    { key: "status", label: "采购状态", required: true },
    { key: "currency", label: "币种", type: "select", required: true, options: PURCHASE_CURRENCY_OPTIONS.map((currency) => ({ label: currency, value: currency })) },
    { key: "releasedAt", label: "下发日期", type: "date" },
  ];
  purchaseOrderConfig.defaultSort = "updatedAt DESC";
}

const purchaseOrderItemConfig = entityConfigs.find((entity) => entity.key === "purchase-order-items");
if (purchaseOrderItemConfig) {
  purchaseOrderItemConfig.listFields = [
    { key: "id", label: "明细ID" },
    { key: "purchaseOrderId", label: "系统采购ID", defaultVisible: false },
    { key: "poNo", label: "PO订单号" },
    { key: "requestNo", label: "来源需求单号" },
    { key: "requestItemId", label: "需求明细" },
    { key: "requestType", label: "类型" },
    { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
    { key: "taxSurcharge", label: "税费加成", type: "money" },
    { key: "unitPrice", label: "含税单价", type: "money" },
    { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
    { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
    { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
    { key: "softwareCoefficient", label: "软件系数", type: "number" },
    { key: "totalCoefficient", label: "总系数", type: "number" },
  ];
  purchaseOrderItemConfig.formFields = [
    { key: "id", label: "明细ID", required: true },
    { key: "purchaseOrderId", label: "系统采购ID" },
    { key: "poNo", label: "PO订单号", required: true },
    { key: "requestNo", label: "来源需求单号" },
    { key: "requestItemId", label: "需求明细ID", required: true },
    { key: "requestType", label: "类型", readonly: true },
    { key: "taxExcludedUnitPrice", label: "不含税单价", type: "money" },
    { key: "taxSurcharge", label: "税费加成", type: "money" },
    { key: "unitPrice", label: "含税单价", type: "money" },
    { key: "capexUnitPrice", label: "采购CAPEX单价", type: "money" },
    { key: "opexUnitPrice", label: "采购OPEX单价", type: "money" },
    { key: "hardwareCoefficient", label: "硬件系数", type: "number" },
    { key: "softwareCoefficient", label: "软件系数", type: "number" },
    { key: "totalCoefficient", label: "总系数", type: "number" },
  ];
}

entityConfigs.push(
  {
    key: "purchase-order-sn-items",
    title: "要货计划SN码",
    table: "purchaseordersnitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/purchase/order-sn-items",
    description: "维护采购订单实例对应的SN码和资产层级信息。",
    showSequence: true,
    filters: [{ key: "keyword", label: "要货计划SN码", placeholder: "请输入PO订单号、SN或固定资产编码" }],
    listFields: [
      { key: "requestNo", label: "要货需求单号" },
      { key: "shippingBatch", label: "发货批次" },
      { key: "deviceVendor", label: "设备厂商" },
      { key: "finalParentSn", label: "最终父项SN" },
      { key: "finalParentPn", label: "甲方最终父项PN" },
      { key: "finalParentPnDescription", label: "最终父项PN描述" },
      { key: "supplierFinalParentCode", label: "供应商最终父项编码" },
      { key: "finalParentCode", label: "甲方最终父项编码" },
      { key: "level", label: "层级" },
      { key: "supplierParentCode", label: "供应商父项编码" },
      { key: "supplierParentSn", label: "供应商父项SN" },
      { key: "parentCode", label: "甲方父项编码" },
      { key: "componentCategory", label: "部件类别" },
      { key: "sn", label: "供应商子项部件SN" },
      { key: "fixedAssetCode", label: "固定资产编码" },
      { key: "poNo", label: "PO" },
      { key: "materialDescription", label: "物料描述" },
      { key: "parentAssetNo", label: "甲方父项固资号" },
      { key: "packingListNo", label: "箱单号" },
      { key: "supplierChildComponentCode", label: "供应商子项部件编码" },
      { key: "customerChildComponentCode", label: "甲方子项部件编码" },
      { key: "supplierChildComponentDescription", label: "供应商子项部件描述" },
      { key: "childComponentOriginalPn", label: "子项部件原厂PN" },
      { key: "childComponentOriginalSn", label: "子项部件原厂SN" },
      { key: "rackUnit", label: "U位" },
      { key: "site", label: "站点" },
      { key: "contactPhone", label: "联系人/电话" },
    ],
    formFields: [
      { key: "id", label: "明细ID", hidden: true },
      { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
      { key: "poNo", label: "PO订单号", hidden: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
      { key: "requestNo", label: "要货需求单号" },
      { key: "shippingBatch", label: "发货批次" },
      { key: "deviceVendor", label: "设备厂商" },
      { key: "finalParentSn", label: "最终父项SN" },
      { key: "finalParentPn", label: "甲方最终父项PN" },
      { key: "finalParentPnDescription", label: "最终父项PN描述" },
      { key: "supplierFinalParentCode", label: "供应商最终父项编码" },
      { key: "finalParentCode", label: "甲方最终父项编码" },
      { key: "level", label: "层级" },
      { key: "supplierParentCode", label: "供应商父项编码" },
      { key: "supplierParentSn", label: "供应商父项SN" },
      { key: "parentCode", label: "甲方父项编码" },
      { key: "componentCategory", label: "部件类别" },
      { key: "sn", label: "供应商子项部件SN", required: true },
      { key: "fixedAssetCode", label: "固定资产编码" },
      { key: "materialDescription", label: "物料描述" },
      { key: "parentAssetNo", label: "甲方父项固资号" },
      { key: "packingListNo", label: "箱单号" },
      { key: "supplierChildComponentCode", label: "供应商子项部件编码" },
      { key: "customerChildComponentCode", label: "甲方子项部件编码" },
      { key: "supplierChildComponentDescription", label: "供应商子项部件描述" },
      { key: "childComponentOriginalPn", label: "子项部件原厂PN" },
      { key: "childComponentOriginalSn", label: "子项部件原厂SN" },
      { key: "rackUnit", label: "U位" },
      { key: "site", label: "站点" },
      { key: "contactPhone", label: "联系人/电话" },
    ],
    defaultSort: "updatedAt DESC",
  },
  {
    key: "purchase-order-plan-items",
    title: "要货计划子",
    table: "purchaseorderplanitems",
    primaryKey: "id",
    navGroup: "隐藏",
    route: "/purchase/order-plan-items",
    description: "维护采购订单的要货计划和供应商交期反馈。",
    showSequence: true,
    filters: [{ key: "keyword", label: "要货计划子", placeholder: "请输入PO订单号、物料或要货计划子ID" }],
    listFields: [
      { key: "sourcePlanId", label: "ID" },
      { key: "quoteReceivedAt", label: "算力供应商收到CEG报价时间", type: "date" },
      { key: "poIssuedAt", label: "算力PO下发时间", type: "date" },
      { key: "receiptProofUploadedAt", label: "签收证明上传时间", type: "date" },
      { key: "logisticsReceivedAt", label: "物流签收时间", type: "date" },
      { key: "ataAt", label: "ATA时间", type: "date" },
      { key: "ata", label: "ATA" },
      { key: "supplierCpd", label: "供应商反馈CPD", type: "date" },
      { key: "material", label: "物料" },
    ],
    formFields: [
      { key: "id", label: "明细ID", hidden: true },
      { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
      { key: "poNo", label: "PO订单号", hidden: true },
      { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
      { key: "requestNo", label: "需求单号", hidden: true },
      { key: "sourcePlanId", label: "要货计划子ID" },
      { key: "quoteReceivedAt", label: "算力供应商收到CEG报价时间", type: "date" },
      { key: "poIssuedAt", label: "算力PO下发时间", type: "date" },
      { key: "receiptProofUploadedAt", label: "签收证明上传时间", type: "date" },
      { key: "logisticsReceivedAt", label: "物流签收时间", type: "date" },
      { key: "ataAt", label: "ATA时间", type: "date" },
      { key: "ata", label: "ATA" },
      { key: "supplierCpd", label: "供应商反馈CPD", type: "date" },
      { key: "material", label: "物料" },
    ],
    defaultSort: "updatedAt DESC",
  },
);

const purchaseOrderSnConfig = entityConfigs.find((entity) => entity.key === "purchase-order-sn-items");
if (purchaseOrderSnConfig) {
  purchaseOrderSnConfig.listFields = purchaseOrderSnFieldSpecs;
  purchaseOrderSnConfig.formFields = [
    { key: "id", label: "明细ID", hidden: true },
    { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
    { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
    { key: "requestNo", label: "需求单号", hidden: true },
    ...purchaseOrderSnFieldSpecs.map((field) =>
      field.key === "poNo" ? { ...field, readonly: true } : field,
    ),
  ];
}

const purchaseOrderPlanConfig = entityConfigs.find((entity) => entity.key === "purchase-order-plan-items");
if (purchaseOrderPlanConfig) {
  purchaseOrderPlanConfig.listFields = purchaseOrderPlanFieldSpecs;
  purchaseOrderPlanConfig.formFields = [
    { key: "id", label: "明细ID", hidden: true },
    { key: "purchaseOrderId", label: "系统采购ID", hidden: true },
    { key: "poNo", label: "PO订单号", hidden: true },
    { key: "purchaseOrderItemId", label: "采购明细ID", hidden: true },
    { key: "requestNo", label: "需求单号", hidden: true },
    ...purchaseOrderPlanFieldSpecs,
  ];
}

function getEntitiesByKeys(keys: string[]) {
  const entityByKey = new Map(entityConfigs.map((entity) => [entity.key, entity]));
  return keys.map((key) => entityByKey.get(key)).filter((entity): entity is EntityConfig => Boolean(entity));
}

entityConfigs.push({
  key: "b6-type-configs",
  title: "B6类型规则",
  table: "b6typeconfigs",
  primaryKey: "b6Type",
  navGroup: "隐藏",
  route: "/finance/b6-type-configs",
  description: "维护B6类型的资金占用、备件服务和结算规则；价格版本确认后会保存规则快照。",
  filters: [{ key: "keyword", label: "B6类型", placeholder: "请输入B6类型、别名或适用范围" }],
  listFields: [
    { key: "b6Type", label: "B6类型" },
    { key: "alias", label: "别名" },
    { key: "scope", label: "适用范围" },
    { key: "defaultFundingMonths", label: "资金占用月数", type: "number" },
    { key: "defaultSpareOccupancyMonths", label: "备件占用月数", type: "number" },
    { key: "overseasSpareServiceAvailable", label: "海外备件服务", type: "boolean" },
    { key: "defaultSpareRate", label: "备件费率（%）", type: "percentage" },
    { key: "spareSettlementMethod", label: "备件结算方式" },
    { key: "status", label: "状态" },
    { key: "sortOrder", label: "排序", type: "number" },
    { key: "updatedAt", label: "更新时间", type: "datetime" },
  ],
  formFields: [
    { key: "b6Type", label: "B6类型", required: true },
    { key: "alias", label: "别名" },
    { key: "scope", label: "适用范围" },
    { key: "fundingCostIncluded", label: "整机价已含资金占用费", type: "boolean" },
    { key: "spareCostIncluded", label: "整机价已含备件费用", type: "boolean" },
    { key: "defaultFundingMonths", label: "默认资金占用月数", type: "number", placeholder: "留空表示待确认" },
    { key: "defaultSpareOccupancyMonths", label: "默认备件占用月数", type: "number", placeholder: "留空表示待确认" },
    { key: "overseasSpareServiceAvailable", label: "提供海外备件服务", type: "boolean" },
    { key: "defaultSpareRate", label: "默认备件费率（%）", type: "percentage" },
    { key: "spareSettlementMethod", label: "备件结算方式", type: "select", options: [
      { label: "备件单独结差", value: "备件单独结差" },
      { label: "按SL模板费率", value: "按SL模板费率" },
      { label: "整机价已含备件费用", value: "整机价已含备件费用" },
    ] },
    { key: "slPricingInstruction", label: "SL模板计价说明", type: "textarea" },
    { key: "notes", label: "备注", type: "textarea" },
    { key: "status", label: "状态", type: "select", required: true, options: [{ label: "启用", value: "启用" }, { label: "停用", value: "停用" }] },
    { key: "sortOrder", label: "排序", type: "number" },
  ],
  defaultSort: "sortOrder ASC, b6Type ASC",
}, {
  key: "capex-pricing",
  title: "CAPEX/OPEX锚定价格",
  table: "capexpricingversions",
  primaryKey: "versionId",
  navGroup: "隐藏",
  route: "/finance/capex-pricing",
  description: "按国家和价格版本维护CAPEX/OPEX锚定价格、完整计算过程和历史快照。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "balance-settlements",
  title: "实例结差",
  table: "balancesettlements",
  primaryKey: "settlementNo",
  navGroup: "隐藏",
  route: "/finance/balance-settlements",
  description: "基于采购CAPEX/OPEX、结差汇率与已确认锚定价格版本生成实例结差来源单，并统一确认各类结差来源单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "balance-final-settlements",
  title: "结差结算单",
  table: "balancesettlementfinals",
  primaryKey: "finalSettlementNo",
  navGroup: "隐藏",
  route: "/finance/balance-final-settlements",
  description: "按国家、结差期间和币种汇集已确认的实例结差与非实例费用结差，形成可追溯的最终结差结算单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "non-instance-settlements",
  title: "非实例费用结差",
  table: "balancesettlements",
  primaryKey: "settlementNo",
  navGroup: "隐藏",
  route: "/finance/non-instance-settlements",
  description: "按备件、清关费、跨境金融税、人力及其他费用类型录入横向明细来源单。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fee-available",
  title: "待初始化内部服务费实例",
  table: "billinginstanceledgers",
  primaryKey: "ledgerId",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-available",
  description: "显示已有月账单台账但尚未生成内部服务费的实例。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fees",
  title: "内部服务费分摊",
  table: "monthlyinternalservicefees",
  primaryKey: "id",
  navGroup: "隐藏",
  route: "/finance/internal-service-fees",
  description: "按合同未税收入减设备采购总成本进行内部服务费分摊，并支持区间调整和月度归档。",
  filters: [{ key: "keyword", label: "内部服务费", placeholder: "请输入国家、批次、需求单、PO或实例编码" }],
  listFields: [
    { key: "writeOffMonth", label: "核算月份", type: "date" },
    { key: "countryCode", label: "国家" },
    { key: "undertakingUnitCode", label: "承接单位" },
    { key: "supplierCode", label: "供应商" },
    { key: "customerCode", label: "客户" },
    { key: "batchName", label: "批次" },
    { key: "requestNo", label: "需求单号" },
    { key: "poNo", label: "PO单号" },
    { key: "deviceCode", label: "实例编码" },
    { key: "internalServiceFeeAmount", label: "内部服务费（未税）", type: "money" },
    { key: "archived", label: "归档状态" },
  ],
  formFields: [],
}, {
  key: "internal-service-fee-adjustments",
  title: "内部服务费调整单",
  table: "internalservicefeeadjustments",
  primaryKey: "adjustmentNo",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-adjustments",
  description: "查看和撤销未涉及归档月份的内部服务费区间调整。",
  filters: [],
  listFields: [],
  formFields: [],
}, {
  key: "internal-service-fee-snapshots",
  title: "内部服务费归档快照",
  table: "internalservicefeesnapshots",
  primaryKey: "snapshotNo",
  navGroup: "隐藏",
  route: "/finance/internal-service-fee-snapshots",
  description: "查看已归档月份的内部服务费快照及冻结明细。",
  filters: [],
  listFields: [],
  formFields: [],
});

const auditListFields: EntityField[] = [
  { key: "createdAt", label: "创建时间", type: "datetime" },
  { key: "updatedAt", label: "更新时间", type: "datetime" },
];

for (const config of entityConfigs) {
  const existingKeys = new Set(config.listFields.map((field) => field.key));
  config.listFields = [
    ...config.listFields,
    ...auditListFields.filter((field) => !existingKeys.has(field.key)),
  ];
}

const financeChildren: NonNullable<NavGroup["children"]> = [
  {
    title: "成本与锚定价格",
    items: getEntitiesByKeys(["b6-type-configs", "capex-pricing", "balance-settlements", "non-instance-settlements", "balance-final-settlements"]),
  },
  {
    title: "月账单管理",
    items: getEntitiesByKeys(["billing-available", "billing-ledgers", "monthly-billing-writeoffs", "billing-statements"]),
  },
  {
    title: "预付款管理",
    items: getEntitiesByKeys([
      "prepayment-available",
      "prepayment-contracts",
      "monthly-prepayment-writeoffs",
      "prepayment-writeoff-adjustments",
    ]),
  },
  {
    title: "服务费核算",
    items: getEntitiesByKeys([
      "service-fees", "service-fee-snapshots", "service-fee-snapshot-items",
      "internal-service-fee-available", "internal-service-fees", "internal-service-fee-adjustments", "internal-service-fee-snapshots",
    ]),
  },
];

export const navGroups: NavGroup[] = [
  {
    title: "财务管理",
    items: financeChildren.flatMap((child) => child.items),
    children: financeChildren,
  },
  {
    title: "合同管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "合同管理"),
  },
  {
    title: "基础信息",
    items: entityConfigs.filter((entity) => entity.navGroup === "基础信息"),
  },
  {
    title: "客户需求",
    items: entityConfigs.filter((entity) => entity.navGroup === "客户需求"),
  },
  {
    title: "采购管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "采购管理"),
  },
  {
    title: "物流管理",
    items: entityConfigs.filter((entity) => entity.navGroup === "物流管理"),
  },
  {
    title: "文档管理",
    items: [
      {
        key: "documents",
        title: "文档库",
        table: "documentfiles",
        primaryKey: "fileId",
        navGroup: "文档管理",
        route: "/documents",
        description: "管理合同、发票等业务文件，支持文件夹、批量上传和下载。",
        filters: [],
        listFields: [],
        formFields: [],
      },
    ],
  },
  {
    title: "数据工具",
    items: [
      {
        key: "system-module-features",
        title: "功能模块管理",
        table: "modulefeatures",
        primaryKey: "moduleKey",
        navGroup: "数据工具",
        route: "/system/module-features",
        description: "管理系统模块的启用和停用状态。",
        filters: [],
        listFields: [],
        formFields: [],
      },
      {
        key: "data-imports",
        title: "数据导入中心",
        table: "importjobs",
        primaryKey: "jobId",
        navGroup: "数据工具",
        route: "/data-imports",
        description: "统一管理模板下载、文件上传、导入预览、错误报告和导入历史。",
        filters: [],
        listFields: [],
        formFields: [],
      },
    ],
  },
];

export function getEntityConfig(key: string): EntityConfig | undefined {
  return entityConfigs.find((entity) => entity.key === key);
}
