"use client";

import { useEffect, useRef, useState } from "react";
import { RefreshCw, Search, Trash2 } from "lucide-react";
import { formatDisplayValue } from "@/lib/display-format";
import { DEFAULT_PAGE_SIZE } from "@/lib/pagination";
import { fetchTableFilterOptions } from "@/lib/table-query-client";
import { PaginationBar } from "./pagination-bar";
import { StickyTable } from "./sticky-table";
import { TableColumnMenu, type TableSortOrder } from "./table-column-menu";
import { Button, Input, Panel } from "./ui";

type Row = Record<string, string | number | boolean | null>;
const columns: Array<[string, string, string?]> = [["adjustmentNo", "调整单号"], ["countryCode", "国家"], ["undertakingUnitCode", "承接单位"], ["supplierCode", "供应商"], ["customerCode", "客户"], ["batchName", "批次"], ["requestNo", "需求单号"], ["poNo", "PO单号"], ["deviceCode", "实例编码"], ["startMonth", "起始月", "date"], ["endMonth", "结束月", "date"], ["monthlyAmount", "每月内部服务费（未税）", "money"], ["reason", "调整原因"], ["confirmedAt", "确认日期", "date"], ["createdAt", "创建日期", "date"], ["updatedAt", "更新日期", "date"]];

export function InternalServiceFeeAdjustmentsPage() {
  const [rows, setRows] = useState<Row[]>([]); const [keyword, setKeyword] = useState(""); const [loading, setLoading] = useState(false); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE); const [total, setTotal] = useState(0); const pageSizeRef = useRef(pageSize);
  const [sortField, setSortField] = useState(""); const [sortOrder, setSortOrder] = useState<TableSortOrder>(""); const [columnFilters, setColumnFilters] = useState<Record<string, string[]>>({});
  async function loadRows(nextPage = page, nextPageSize = pageSizeRef.current, queryState = { sortField, sortOrder, columnFilters }) { setLoading(true); try { const params = new URLSearchParams({ page: String(nextPage), pageSize: String(nextPageSize) }); if (keyword.trim()) params.set("keyword", keyword.trim()); if (queryState.sortField && queryState.sortOrder) { params.set("sortField", queryState.sortField); params.set("sortOrder", queryState.sortOrder); } for (const [field, values] of Object.entries(queryState.columnFilters)) for (const value of values) params.append(`filter.${field}`, value); const response = await fetch(`/api/internal-service-fees/adjustments/list?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "调整单加载失败"); setRows(data.rows ?? []); setTotal(Number(data.total ?? 0)); setPage(Number(data.page ?? nextPage)); } catch (error) { alert(error instanceof Error ? error.message : "调整单加载失败"); } finally { setLoading(false); } }
  function refreshTableQuery(next: { sortField?: string; sortOrder?: TableSortOrder; columnFilters?: Record<string, string[]> }) { const nextState = { sortField: next.sortField ?? sortField, sortOrder: next.sortOrder ?? sortOrder, columnFilters: next.columnFilters ?? columnFilters }; setSortField(nextState.sortField); setSortOrder(nextState.sortOrder); setColumnFilters(nextState.columnFilters); setPage(1); void loadRows(1, pageSizeRef.current, nextState); }
  useEffect(() => { void loadRows(); }, []);
  async function cancel(adjustmentNo: string) { if (!confirm(`确认撤销 ${adjustmentNo} 吗？未归档月份会按剩余金额重新分摊。`)) return; const response = await fetch(`/api/internal-service-fees/adjustments/${encodeURIComponent(adjustmentNo)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return alert(data.error ?? "撤销失败"); await loadRows(); }
  return <div className="space-y-5"><div><h1 className="text-xl font-medium text-[#303133]">内部服务费调整单</h1><p className="mt-1 text-sm text-[#909399]">查看通过区间调整创建的固定月度内部服务费记录；涉及已归档月份的调整不可撤销。</p></div><Panel><div className="flex flex-wrap items-center gap-2 border-b border-[#ebeef5] p-4"><Input placeholder="搜索调整单、需求单、PO或实例编码" value={keyword} onChange={(event) => setKeyword(event.target.value)} /><Button tone="primary" onClick={() => { setPage(1); void loadRows(1, pageSizeRef.current); }}><Search size={15} />查询</Button><Button onClick={() => void loadRows()}><RefreshCw size={15} />刷新</Button></div><StickyTable className="table-scroll overflow-auto" tableKey="internal-service-fee-adjustments"><table className="w-full min-w-[1540px] border-collapse text-sm"><thead className="bg-[#f5f7fa] text-[#303133]"><tr>{columns.map(([key, label]) => <th className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3 text-left font-medium" key={key}><TableColumnMenu column={{ key, label, sortable: true, filterable: true }} sortOrder={sortField === key ? sortOrder : ""} filterValues={columnFilters[key] ?? []} loadOptions={(keyword) => fetchTableFilterOptions("/api/internal-service-fees/adjustments/list", key, keyword, {}, columnFilters)} onSort={(order) => refreshTableQuery({ sortField: order ? key : "", sortOrder: order })} onFilter={(values) => refreshTableQuery({ columnFilters: { ...columnFilters, [key]: values } })} /></th>)}<th className="w-[104px] min-w-[104px] border-b border-[#ebeef5] px-3 py-3 text-left font-medium">操作</th></tr></thead><tbody>{rows.map((row) => <tr className="hover:bg-[#fafafa]" key={String(row.adjustmentNo)}>{columns.map(([key, , type]) => <td className="whitespace-nowrap border-b border-r border-[#ebeef5] px-3 py-3" key={key}>{formatDisplayValue(row[key], type)}</td>)}<td className="whitespace-nowrap border-b border-[#ebeef5] px-3 py-3"><Button className="whitespace-nowrap" tone="danger" onClick={() => void cancel(String(row.adjustmentNo))}><Trash2 size={15} />撤销</Button></td></tr>)}{!rows.length && <tr><td className="py-12 text-center text-[#909399]" colSpan={columns.length + 1}>{loading ? "加载中..." : "暂无内部服务费调整单"}</td></tr>}</tbody></table></StickyTable><PaginationBar page={page} pageSize={pageSize} total={total} onPageChange={(next) => { setPage(next); void loadRows(next, pageSizeRef.current); }} onPageSizeChange={(next) => { pageSizeRef.current = next; setPage(1); void loadRows(1, next); }} /></Panel></div>;
}
